//
//  ContentViewModel.swift
//  GreenSavings
//
//  Created by GreenSavingsTeam on 16/10/23.
//

import SwiftUI
import Foundation

class ContentViewModel{
    
    let navigationTitleText: String = "My green savings"
    
    let greetingText: String = "Hey! \nNice to meet you, eco hero! \nHere you can learn how to save you money and planet. Earn green coins and spend them to plant you own tree!"
    
    let items: [ItemViewModel] = [ItemViewModel(id: 1, name: "Electricity", foregroundColor: Color(red: 1, green: 0.65, blue: 0.7), imageName: "electricity", learningMaterials: [LearningMaterials(learningMaterialsTitle: "Information", unlock: true, imageName: "Articles1Electricity", textMaterials: "Reducing energy waste is good for the environment and good for profits. There are many ways to reduce energy waste in the home. \nHow does reducing energy waste help the environment? \nElectricity is generated by burning fossil fuels, it produces greenhouse gases that harm the planet. By minimizing energy waste, power plants burning fossil fuels emit fewer pollutants, reducing the greenhouse effect, which leads to higher temperatures and extreme weather conditions. Additionally, conserving energy resources like trees, coal, and natural gas is vital. Wasted energy also damages biodiversity by destroying natural habitats. Adopting practices to reduce electricity waste can significantly lower carbon emissions and contribute to the fight against pollution and climate change."),                                      LearningMaterials(learningMaterialsTitle: "What to buy"),LearningMaterials(learningMaterialsTitle: "Article"), LearningMaterials(learningMaterialsTitle: "Video"), LearningMaterials(learningMaterialsTitle: "Article"), LearningMaterials(learningMaterialsTitle: "Curiosity"), LearningMaterials(learningMaterialsTitle: "What to buy")]),
                                  
                                  ItemViewModel(id: 2, name: "Recycling", foregroundColor: .red, imageName: "recycling", learningMaterials: [LearningMaterials(learningMaterialsTitle: "Information"), LearningMaterials(learningMaterialsTitle: "What to buy"), LearningMaterials(learningMaterialsTitle: "Article"), LearningMaterials(learningMaterialsTitle: "Video"), LearningMaterials(learningMaterialsTitle: "Article"), LearningMaterials(learningMaterialsTitle: "Curiosity"), LearningMaterials(learningMaterialsTitle: "What to buy")]),
                                  ItemViewModel(id: 3, name: "Pollution", foregroundColor: .yellow, imageName: "pollution", learningMaterials: [LearningMaterials(learningMaterialsTitle: "Information"), LearningMaterials(learningMaterialsTitle: "What to buy"), LearningMaterials(learningMaterialsTitle: "Article"), LearningMaterials(learningMaterialsTitle: "Video"), LearningMaterials(learningMaterialsTitle: "Article"), LearningMaterials(learningMaterialsTitle: "Curiosity"), LearningMaterials(learningMaterialsTitle: "What to buy")])
                                  
    ]
    
    
    //i have to set backgroundColor for each learningMaterialsTitle, i have to set imageName and textName for each learningMaterialsTitle
    
    
}
