//
//  LearningMaterials.swift
//  GreenSavings
//
//  Created by Davide Galdiero on 20/10/23.
//

import Foundation
import SwiftUI

struct LearningMaterials: Identifiable, Hashable {
    var id = UUID()
    var materialType: LearningType
    var backgroundColor: Color = .cyan
    var learningMaterialsTitle: String
    var isUnlocked: Bool
    var isLearned: Bool
//    var imageName: String = " " // use real info
//    var textMaterials: String = " " // use real info
    var giftPlant: PlantCardModel
}

extension LearningMaterials: Equatable {
    static func == (lhs: LearningMaterials, rhs: LearningMaterials) -> Bool {
        return lhs.id == rhs.id
    }
}

extension LearningMaterials {
    func hash(into hasher: inout Hasher) {
        hasher.combine(id)
    }
}

enum LearningType {
    case info
    case article
    case tips
    case video
    
    var title: String {
        switch self {
        case .article:
            return "Educational article"
        case .info:
            return "General information"
        case .tips:
            return "Tips"
        case .video:
            return "Educational video"
        }
    }

    var assetName: String {
        switch self {
        case .article:
            return "Materials/Electricity"
        case .info:
            return ""
        case .tips:
            return ""
        case .video:
            return "Materials/imageVideo"//"elecrticityVideo"
        }
    }
    
    var description: String {
        switch self {
        case .article:
            return "Reducing energy waste is good for the environment and good for profits. There are many ways to reduce energy waste in the home. \nHow does reducing energy waste help the environment?\n Electricity is generated by burning fossil fuels, it produces greenhouse gases that harm the planet. By minimizing energy waste, power plants burning fossil fuels emit fewer pollutants, reducing the greenhouse effect, which leads to higher temperatures and extreme weather conditions. Additionally, conserving energy resources like trees, coal, and natural gas is vital. Wasted energy also damages biodiversity by destroying natural habitats. Adopting practices to reduce electricity waste can significantly lower carbon emissions and contribute to the fight against pollution and climate change."
        case .info:
            return  ""
        case .tips:
            return   ""
        case .video:
            return  "Watch the video to learn how to use household electrical appliances more effectively."
        }
    }
}
